name: dictionnaire_moundang
description: Lexique des mots et locutions en langue Moundang avec traduction en Français.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  card_settings: ^1.7.0
  http: ^0.12.0+4
  url_launcher: ^5.4.2
  introduction_screen: ^1.0.8
  shared_preferences: ^0.5.7
  flutter_launcher_icons: ^0.7.5
  flutter_share: ^1.0.2+1
  flutter_automation: ^1.3.3
  #pull_to_refresh: ^1.5.8
  #search_app_bar: ^1.0.2+2



#flutter icon
flutter_icons:
  image_path: "assets/icone/icone.png"
  android: "launcher_icon"
  image_path_android: "assets/icone/icone.png"
    #android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icone/icone.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icone/icone.png" # only available for Android 8.0 devices and above
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: empire
      fonts:
        - asset: assets/font/My Empire Wont Fall.ttf
    - family: cadela
      fonts:
        - asset: assets/font/Caladea-Italic.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/icone/icone.png
     - assets/icone/icone1.png
     - assets/icone/intro.gif
     - assets/icone/intro2.gif
     - android/app/src/main/res/drawable/splash_screen.png
     #- android/app/src/main/res/drawable/splash_screen.jpg
     - assets/Dico_Moundang.json
  #  - assets/logo.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
